### ISSUE TITLE
version 0.1.0 brake add_multiple_errors

### ISSUE THREAD

**Issue by vdaubry** [nebulab/simple_command#23]
When calling add_multiple_errors with an error hash i get `NoMethodError: undefined method `each' for #<String:0x00007ff1cd1a8710>`

I have an error object from another command object, when i call add_multiple_errors it works with version 0.9.0 and raises a `NoMethodError` error with 0.1.0:

```
>command.errors
:error=>["21004 The shared secret you provided does not match the shared secret on file for your account."]}
>errors.add_multiple_errors(command.errors)
NoMethodError: undefined method `each' for #<String:0x00007ff1cd1a8710>
```

**Comment by kennyadsl** [comment]
Thanks for reporting, can you please provide a breaking spec for this scenario?
